//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequests
    {
        public int UserID { get; set; }
        public int FutureFriendId { get; set; }
        public string Message { get; set; }
        public string TimeStamp { get; set; }
        public string ApproveFlag { get; set; }
        public string RejectFlag { get; set; }
        public string BlockFlag { get; set; }
        public string SpamFlag { get; set; }
    
        public virtual Friends Friends { get; set; }
    }
}
